version: '2'
services:
  web:
    image: nginx
    volumes:
      - ./nginx-site.conf:/etc/nginx/conf.d/nginx-site.tmp
    environment:
      NGINX_PORT: 80
      AVATAR_PORT: 5000
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx-site.tmp > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8080:80
    links:
      - app
  app:
    image: dolfelt/avatar-go:latest
    environment:
      AVATAR_AWSBUCKET: bucket.example.com
      AVATAR_DBHOST: db
      AVATAR_PORT: 5000
    # command: /avatar serve
    ports:
      - 5000:5000
    links:
      - db
    volumes:
      - .:/go/src/github.com/dolfelt/avatar-go
  db:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: avatars
    ports:
      - 5432:5432
    expose:
      - 5432
